"""init tables

Revision ID: 9f2013299b4f
Revises: 
Create Date: 2026-09-08 19:32:40.372916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2013299b4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_utilisateur_id'), 'utilisateur', ['id'], unique=False)
    op.create_table('matiere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matiere_id'), 'matiere', ['id'], unique=False)
    op.create_table('cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matiere_id'], ['matiere.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cours_id'), 'cours', ['id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(), nullable=False),
    sa.Column('chemin_fichier', sa.String(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=True),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_cours_id'), table_name='cours')
    op.drop_table('cours')
    op.drop_index(op.f('ix_matiere_id'), table_name='matiere')
    op.drop_table('matiere')
    op.drop_index(op.f('ix_utilisateur_id'), table_name='utilisateur')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
